---
- name: create directory identityiq
  file: path=/usr/share/tomcat/webapps/identityiq state=directory
  
- name: unpack war file
  unarchive: src=../files/identityiq.war dest=/usr/share/tomcat/webapps/identityiq remote_src=no
  
- name: update sql-script
  template: src=../templates/create.mysql dest=/usr/share/tomcat/webapps/identityiq/WEB-INF/database/create_identityiq_tables-7.0.mysql owner=tomcat group=tomcat
  
- name: create database 
  shell: mysql -u root --password={{ mysql_root_password }} < /usr/share/tomcat/webapps/identityiq/WEB-INF/database/create_identityiq_tables-7.0.mysql > /usr/share/tomcat/webapps/identityiq/WEB-INF/database/mysql.out

- name: update connect to database
  template: src=../templates/iiq.properties dest=/usr/share/tomcat/webapps/identityiq/WEB-INF/classes/iiq.properties owner=tomcat group=tomcat
  # replace password in file
  
# - name: change permissions iiq
#   file: path=/usr/share/tomcat/webapps/identityiq/WEB-INF/bin/iiq mode="u=rwx,g=r"
#   ignore_errors: yes  
  
# ./iiq console -j -c import init.xml -f out.log

- name: restart tomcat
  systemd: name=tomcat state=restarted