---

- name: preparation to install java
  get_url: url={{ jdk_url_rep }} dest=/opt/jdk8.rpm headers='Cookie:oraclelicense=accept-securebackup-cookie'
  
- name: install java
  yum: name=/opt/jdk8.rpm state=present validate_certs=no
  
- name: delete rmp of java
  file: path=/opt/jdk8.rpm state=absent