---

- name: preparation to install MySQL
  get_url: url={{ mysql_url_rep }} dest=/opt/mysql.rpm
  
- name: add MySQL repository
  yum: name=/opt/mysql.rpm state=present validate_certs=no
  
- name: install MySQL
  yum: name={{ item }} state=latest
  with_items:
    - MySQL-python
    - mysql
    - mysql-server
  
- include: password.yml
  
- name: start MySQL
  systemd: name=mysqld enabled=yes state=started

# - name: update password
#  command: >
#    mysqladmin -u root password {{ mysql_root_password }}
  
  # update expared password
- name: update root password
  command: >
    mysqladmin -u root password {{ mysql_root_new_password }}
    
- name: copy .my.cnf file with root password credentials
  template: src=../templates/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
      
# fatal: [identityIQ]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to database, check login_user and login_password are corrector /root/.my.cnf has the credentials. Exception message: (1862, 'Your password has expired. To log in you must change it using a client that supports expired passwords.')"}
- name: delete anonymous user from MySQL server
  mysql_user: user="" host="identityIQ" state="absent"
  ignore_errors: yes

# fatal: [identityIQ]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to database, check login_user and login_password are correct or/root/.my.cnf has the credentials. Exception message: (1862, 'Your password has expired. To log in you must change it using a client that supports expired passwords.')"}
- name: delete anonymous MySQL server user for localhost
  mysql_user: user="" state="absent"
  ignore_errors: yes

#fatal: [identityIQ]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1862, 'Your password has expired. To log in you must change it using a client that supports expired passwords.')"}
- name: remove the MySQL test database
  mysql_db: db=test state=absent
  ignore_errors: yes
  
- name: delete rmp of MySQL
  file: path=/opt/mysql.rpm state=absent