---

- name: preparation to install MySQL
  get_url: url={{ mysql_url_rep }} dest=/opt/mysql.rpm
  
- name: add MySQL repository
  yum: name=/opt/mysql.rpm state=present validate_certs=no
  
- name: install MySQL
  yum: name={{ item }} state=latest
  with_items:
    - MySQL-python
    - mysql
    - mysql-server
  
- include: password.yml
  
- name: start MySQL
  systemd: name=mysqld enabled=yes state=started
  
- name: copy .new_my.cnf file with root password credentials
  template: src=../templates/new_my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: delete anonymous user from MySQL server
  mysql_user: user="" host="identityIQ" state="absent"

- name: delete anonymous MySQL server user for localhost
  mysql_user: user="" state="absent"

- name: remove the MySQL test database
  mysql_db: db=test state=absent
  
- name: delete rmp of MySQL
  file: path=/opt/mysql.rpm state=absent