---

# set root password. see http://stackoverflow.com/questions/38433295/unable-to-change-password-for-root-account-ansible
- name: stop MySQL
  service: name=mysqld state=stopped
  
- name: set environment variables
  shell: systemctl set-environment MYSQLD_OPTS="--skip-grant-tables"

- name: start MySQL
  service: name=mysqld state=started

- name: sql query
  command:  mysql -u root --execute="UPDATE mysql.user SET authentication_string = PASSWORD('{{ mysql_root_password }}') WHERE User = 'root' AND Host ='localhost';"  
      
- name: sql query flush
  command:  mysql -u root --execute="FLUSH PRIVILEGES"
  
- name: stop MySQL
  service: name=mysqld state=stopped
  
- name: unset environment variables
  shell: systemctl unset-environment MYSQLD_OPTS
  
- name: start MySQL
  systemd: name=mysqld enabled=yes state=started
  
  # update expared password
- name: copy .old_my.cnf file with root password credentials
  template: src=../templates/old_my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  
- name: update root password
  command: >
    mysqladmin -u root password {{ mysql_root_new_password }}
    